//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamionesWebMVC_v01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camione()
        {
            this.Rutas = new HashSet<Ruta>();
        }
    
        public int IdCamion { get; set; }
        public string Matricula { get; set; }
        public string TipoCamion { get; set; }
        public Nullable<int> Modelo { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<double> Kilometraje { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
        public string UrlFoto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruta> Rutas { get; set; }
    }
}
