//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamionesWebMVC_v01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeNeContext1 : DbContext
    {
        public GeNeContext1()
            : base("name=GeNeContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camione> Camiones { get; set; }
        public virtual DbSet<Chofere> Choferes { get; set; }
        public virtual DbSet<Ruta> Rutas { get; set; }
    
        public virtual int Delete_Camion(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Camion", idCamionParameter);
        }
    
        public virtual int Delete_Chofer(Nullable<int> idChofer)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Chofer", idChoferParameter);
        }
    
        public virtual int Delete_Ruta(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Ruta", idRutaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Existe_Licencia(string licencia)
        {
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Existe_Licencia", licenciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Existe_Matricula(string matricula)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Existe_Matricula", matriculaParameter);
        }
    
        public virtual int Insert_Camion(string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, string urlFoto, Nullable<bool> disponibilidad)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Camion", matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, urlFotoParameter, disponibilidadParameter);
        }
    
        public virtual int Insert_Chofer(string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Chofer", nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter);
        }
    
        public virtual int Insert_Ruta(Nullable<int> idChofer, Nullable<int> idCamion, string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<bool> aTiempo, Nullable<double> distancia)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Ruta", idChoferParameter, idCamionParameter, origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, aTiempoParameter, distanciaParameter);
        }
    
        public virtual int Insertar_Chofer(string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insertar_Chofer", nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter);
        }
    
        public virtual ObjectResult<Listar_Camiones_Result> Listar_Camiones(Nullable<bool> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_Camiones_Result>("Listar_Camiones", disponibilidadParameter);
        }
    
        public virtual ObjectResult<Listar_Choferes_Result> Listar_Choferes(Nullable<bool> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Listar_Choferes_Result>("Listar_Choferes", disponibilidadParameter);
        }
    
        public virtual ObjectResult<ListarRutas_Result> ListarRutas(Nullable<bool> aTiempo)
        {
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarRutas_Result>("ListarRutas", aTiempoParameter);
        }
    
        public virtual ObjectResult<Obtener_Camion_PorID_Result> Obtener_Camion_PorID(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Camion_PorID_Result>("Obtener_Camion_PorID", idCamionParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Update_Camion(Nullable<int> idCamion, string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, Nullable<bool> disponibilidad, string urlFoto)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Camion", idCamionParameter, matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, disponibilidadParameter, urlFotoParameter);
        }
    
        public virtual int Update_Chofer(Nullable<int> idChofer, string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Chofer", idChoferParameter, nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter);
        }
    
        public virtual int Update_Ruta(Nullable<int> idRutas, Nullable<int> idChofer, Nullable<int> idCamion, string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<bool> aTiempo, Nullable<double> distancia)
        {
            var idRutasParameter = idRutas.HasValue ?
                new ObjectParameter("IdRutas", idRutas) :
                new ObjectParameter("IdRutas", typeof(int));
    
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Ruta", idRutasParameter, idChoferParameter, idCamionParameter, origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, aTiempoParameter, distanciaParameter);
        }
    }
}
