//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamionesWebMVC_v01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        public int IdRutas { get; set; }
        public Nullable<int> IdChofer { get; set; }
        public Nullable<int> IdCamion { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaLlegada { get; set; }
        public Nullable<bool> ATiempo { get; set; }
        public Nullable<double> Distancia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Camione Camione { get; set; }
        public virtual Chofere Chofere { get; set; }
    }
}
